export const MAIN_WALLET_PUBKEY =
  "HsKWuot1ZK39CEZoLFWR6UCwQQZq21wNmWxqqKXt8iGB";

export const ACCOUNT_PRIVATE_KEY =
  "5ZbQSr9uwwQzUrWkbugkSmmfVG2mzgHbrCbCsk9obgJs9g3oDGh42GDycJUBQAimNQcBzhXsd9Mb6X7SsYrPBJFB";